### ISSUE TITLE
Update mattermost-plugin-giphy to 2.1.1

### ISSUE THREAD

**Issue by moussetc** [mattermost/mattermost-marketplace#236] opened 2021-11-13 22:45 UTC
#### Summary

- Fix: make Gfycat results much more pertinent (previously, a lot of Gfycat results were mistakenly ignored)
- Notify user with ephemeral message send by plugin bot when no (more) GIF was found 
- Fix error when reaching the end of Gfycat search results (https://github.com/moussetc/mattermost-plugin-giphy/issues/47)
- When "Full URL display", display attribution mark on new line (https://github.com/moussetc/mattermost-plugin-giphy/issues/46)

Note: the purpose of this version is to bring these bug fixes to the maximum of users, including "older" versions, which is why the MM dependency is not upgraded.

#### Review reference
Commit [c26638e](https://github.com/moussetc/mattermost-plugin-giphy/commit/c26638e1909f282d9d7c2b5c1834f75115589362)

## Checklist

- [x] [All requirements](https://developers.mattermost.com/extend/plugins/community-plugin-marketplace/#requirements-for-adding-community-plugin-to-the-marketplace) are still met.
- [x] The release also has to follow [Semantic Versioning](https://semver.org/). For plugins in particular this means:
  - If the plugin exposes a public API, breaking changes to the API require a major version bump.
  - If an update requires manual migration actions from the System Admin, a major version bump is required.
- [x] A changelog has been published. The link to it is noted via `release_notes_url` in the manifest.

**Comment by hanzei** [comment] 2021-11-15 12:13
## Process checklist
- [x] Create PR to merge changes from upstream into `master`.
- [x] Request reviews.
- [ ] [Cut plugin release](https://developers.mattermost.com/internal/plugin-release-process).
- [ ] Add release to Marketplace.

**Comment by hanzei** [comment] 2021-11-15 12:14
Thanks @moussetc for the plugin update :+1:

**Comment by moussetc** [comment] 2022-10-07 15:42
Hello there! Any news on this plugin update? :)

**Comment by moussetc** [comment] 2022-10-07 15:45
A new 2.1.2 version of the plugin has been released in the 11 months since opening this update issue, any chance to have it be integrated in the marketplace?

**Comment by hanzei** [comment] 2022-10-07 18:50
Hi @moussetc,

First of all: Sorry this takes so long. A simple update to a plugin should not take a year to get the Marketplace.

I've reached out to the QA testers again and asked them to put the plugin on top of there review queue.

**Comment by hanzei** [comment] 2022-10-07 18:52
On a more general note: The review process for plugin takes to long. We are working on identifying potential way to speed up the process without reducing the quality of reviews. @asatkinson and I are working on this effort. We will keep you updated.

**Comment by moussetc** [comment] 2022-10-07 19:02
Thank you for the update. I understand that the process can take a long time, but more than 4 months is not really workable let alone a year.

For example, since i opened this issue  there was a change in a dépendance API (Tenor) that broke the plugin for all people that use this gif provider, so I had to push another release quickly. I have not even tried to open an issue on the marketplace to integrate it because of radio silence on this current update request.
The QA will thus fail on this 2.1.1 update, at least for all tests using Tenor.

Please advise: what's the wanted process when review takes longer than new releases?

**Comment by floviolleau** [comment] 2022-12-08 08:55
Hi,

Just putting my 10¢ here to get it soon on the marketplace.
We have no rights to install from a tarball (only from marketplace) so we are expecting it a lot

Thanks

**Comment by moussetc** [comment] 2023-01-28 13:35
Hello @hanzei ,
Has there been advances on this CI issue? Also, could you please tell me, if I were to submit a new version of this plugin to the Marketplace, or another plugin altogether based on the Mattermost starter template, would they also be affected by this issue?

**Comment by hanzei** [comment] 2023-02-05 11:56
Hey @moussetc,

The CI issue is caused by the `Choose a MPAA-style rating` setting. The first setting, `No rating (no content filtering)`, has it's `value` set to `""` which is an invalid value according to the `IsValid()` method. The documentation doesn't state that it's valid though (https://developers.mattermost.com/integrate/plugins/manifest-reference/#settings_schema.settings.options.value). I've submitted https://github.com/mattermost/mattermost-marketplace/pull/340 to unblock your plugin from going into the Marketplace.
Would you be open on updating your plugin to use a non-empty value in the settings list? That would make the next release easier to get into the Marketplace.

> Also, could you please tell me, if I were to submit a new version of this plugin to the Marketplace, or another plugin altogether based on the Mattermost starter template, would they also be affected by this issue?

The issue has nothing to do with the starter template. Feel free to submit another plugin. Looking forward to it! :+1:

**Comment by hanzei** [comment] 2023-02-05 11:57
And if there is a new version of Giphy, you can also submit it. I hope to resolve the CI issue in the next week.

**Comment by moussetc** [comment] 2023-02-05 18:52
Hey @hanzei ,

Thank you for the update (and the work required to troubleshoot and fix this issue!).

I will add not using the "" value in the plugin settings in the next release of the plugin (which I am more motivated to work on, now that the previous-previous one is very nearly published :p ).

I am wondering if it might be worth to add a check with manifest.IsValid() on the OnActivate() hook, both in my plugin (I will probably do it to avoid further issues) AND in the mattermost-plugin-starter-template, do yo think the second one would be worth it?

**Comment by moussetc** [comment] 2023-03-06 22:21
Hello @hanzei ,

Any news since last month's ?

**Comment by moussetc** [comment] 2023-03-23 20:37
Hello @hanzei ,

Any news since February ?

**Comment by esethna** [comment] 2023-07-17 21:18
Linking related conversation: https://github.com/mattermost/mattermost-marketplace/issues/365#issuecomment-1638893037

**Comment by esethna** [comment] 2023-07-17 21:37
Closing following the related conversation above ^

**Closed by esethna** 2023-07-17 21:37 UTC
Labels: Plugin/Update
