### ISSUE TITLE
Write unit tests for `generate` and `add` commands

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-marketplace#127] opened 2020-10-09 08:07 UTC
#### Summary

The CLI commands `generate` and `add` are currently not covered by unit tests.

In order to test the code, the GitHub client must be mocked in the test. You can use `gomock` as the mocking framework. If you have any questions, join the [Integrations channel](https://community.mattermost.com/core/channels/integrations) on our community server.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-29272

**Comment by mickmister** [comment] 2020-10-09 08:08
@hanzei Do you know how I can use the `Hacktoberfest` and `Up For Grabs` labels in this repo?

**Comment by hanzei** [comment] 2020-10-09 08:10
@mickmister Just added them

**Comment by jmk-198xtsuga** [comment] 2022-10-02 14:01
If this issue is still on the to-do list, I'd like to help out!

**Comment by mickmister** [comment] 2022-10-02 15:52
Sure it's all yours! Thanks @jmk-198xtsuga!!

**Comment by jmk-198xtsuga** [comment] 2022-10-10 17:10
Research notes:
- marketplace is building with the [Google Go-GitHub v28](https://pkg.go.dev/github.com/google/go-github/v28/github) package ([source on GitHub](https://github.com/google/go-github)) as an API client, which interacts with the [Github v3 API](https://docs.github.com/en/rest/overview/endpoints-available-for-github-apps).
- The mattermost-marketplace command line generator invokes the API client for:
    - main.go:
        - client.Repositories.Get(context, org, repositoryName) ([client source](https://github.com/google/go-github/blob/master/github/repos.go)) ([client test](https://github.com/google/go-github/blob/master/github/repos_test.go)) ([API docs](https://docs.github.com/en/rest/repos/repos#get-a-repository))
        - client.Repositories.ListReleases(context, org, repositoryName, options) ([client source](https://github.com/google/go-github/blob/master/github/repos_releases.go)) ([client test](https://github.com/google/go-github/blob/master/github/repos_releases_test.go)) ([API docs](https://docs.github.com/en/rest/releases/releases#list-releases))

(links to client's own test files not necessarily to directly copy/paste their code for mine, but more to demo how they tested their own client, for inspiration)

**Comment by mickmister** [comment] 2022-10-12 16:25
In order to mock these methods out in unit tests, we can create an interface that implements these methods, and use [gomock](https://github.com/golang/mock) to implement mock versions of these methods. 

- Example interface to be mocked - https://github.com/mattermost/mattermost-plugin-apps/blob/78beae6cedca6de6e91fb196434f754b9964de2c/server/mmclient/client.go#L9
- Using `gomock`'s CLI tool to generate mocks - https://github.com/mattermost/mattermost-plugin-apps/blob/78beae6cedca6de6e91fb196434f754b9964de2c/build/custom.mk#L27
- Instantiating a mock in a unit test - https://github.com/mattermost/mattermost-plugin-apps/blob/b8285d143c218bb778bbb19fe0989119491d2064/server/proxy/expand_test.go#L270

**Comment by jmk-198xtsuga** [comment] 2022-10-13 01:43
Thanks @mickmister for the links!  That will help quite a bit, I was still digging through how the whole `gomock` system works, and these links alone make a solid jump forward in that understanding.

I haven't checked things in (even on [my own fork](https://github.com/jmk-198xtsuga/mattermost-marketplace) of the repo) because I'm still exploring the best way to go about the mocks and unit tests, and particularly the returned github::`Repository` structures.  I did now check in one commit on a branch called sandbox, to show what I'm referring to below.  But for an update on that:
- I've been starting out looking at main.go's `generatorCmd` and working on how to mock out the "external" part of what it is doing.  In particular, the first thing on my list was getting the list of repositories and releases.  Then I noticed that those are not completely trivial...
- I've found the best way to instantiate a `Repository` is to actually do a `httptest` server with a custom handler for the API endpoint, feeding in JSON (and by using `golang`'s `httptest`, can avoid any actual network traffic), and letting the Go-GitHub client do the work.  This is easier for me than directly defining a `Repository` because the `Repository` structure has mostly pointers instead of the actual variables (i.e. `*int` or `*string`) so that they can be nullable (i.e. value of `nil`) when the JSON object was incomplete.  I'm still learning the concepts of golang so there may be an easier way to directly instantiate this, but for practical reasons I found it faster to copy/paste the JSON and let the Go-GitHub client do the work for me.
- For the list of `Repository`s, I'm planning to do the exact same JSON and GoGitHub workaround, and probably will find similar reasons to do the same thing for releases.
- Once I can get those objects available, then I'll actually be able to go after the "guts" of what these are doing, to test for what I would consider expected behavior.  At that point you'll probably start seeing activity on my fork.
- Also, because the Repository and probably other github client struct's have these nullable fields, I can probably carve down the JSON I'm testing with to only have relevant fields, because it may not break anything to omit the extra "fluff".  Also, I can change the mock to use realistic (or actual real, saved at one point in time) JSON for the 12 repositories listed in `repositoryNames` in `generatorCmd`.

**Comment by jmk-198xtsuga** [comment] 2022-10-16 18:04
Yes, finally getting more time to dig into it, and for the original question of how to get the original `Repository` or `RepositoryRelease` elements to check that cmd > generator > main.go functions are correctly unpacking the results from the github client:
- `getReleases()`
- `getReleasePlugins()`

Since `github.Client` is not an interface, the easiest way around that is to do the `httptest` workaround, because they interact directly with said `github.Client`.  The other functions should be able to be used with the `gomock` tools because then I can do interfaces on things actually in this project.

Also, after thinking more on it, the eventual way of constructing the github objects, with them having large quantities of pointers, is that I'll make a constructor for them using only the information relevant to `generatorCmd`, and have the constructor `new(T)` allocate what is needed and set it to whatever values are useful for the test.

**Comment by jmk-198xtsuga** [comment] 2022-10-17 00:25
Now that I've dug into the interface pattern for gomock, and looked back at the cmd > generator files, in fact `generatorCmd` also does not have interfaces.  I'll check in on the integrations channel when I have time to chat, and figure out if an interface is the best solution here.

Also disclaimer, I'm not natively a Go programmer (I prefer the C family, and can do java, javascript, etc), so I may be missing some details.

Anyway, I've updated my sandbox with a reliable way to generate responses to the github client Repositories.Get() call without online http traffic.

**Comment by jmk-198xtsuga** [comment] 2022-10-20 03:29
Alright, now at least for the manual mock approach (ignoring automatic mock generation by `gomock`), I'm comfortable saying I've met my 4 goals before actually pointing tests at `generatorCmd` and `add`:
- I've got enough understanding of the Go language to effectively write the tests and data structures I need
- I've been able to make mocks for the _external_ items, particularly the data objects returned by the GitHub client
- I've been able to make reasonably structured unit tests, with itemized steps, and
- I've been able to isolate the mocks and tests into a separate module from what they're testing, and particularly from `main`

I'll now dig into the `generator` and supporting functions, and on a non-"sandbox" branch.

**Comment by mickmister** [comment] 2022-10-20 07:24
@jmk-198xtsuga Feel free to submit a draft PR if you want early feedback on your work :+1:

**Comment by jmk-198xtsuga** [comment] 2022-10-30 02:51
@mickmister Thanks for the offer!  I'm still a fair distance away from having a "thorough" test, or even filling out tests for the different functions in [cmd/generator/main.go](https://github.com/mattermost/mattermost-marketplace/blob/master/cmd/generator/main.go), but I'll go ahead and open a PR to showcase where I'm at so far.

I'm not finding much free time to make progress on things, so if you have anyone else that wants to jump in the invitation is open.  That said, whenever I do find some downtime I do enjoy chipping away at this, and will continue work when I can.

Will add commentary to pull request once open.

**Comment by esethna** [comment] 2023-07-17 19:33
Closing as the JIRA ticket is completed

**Closed by esethna** 2023-07-17 19:33 UTC
Labels: Type/Enhancement, Help Wanted, Hacktoberfest, Good First Issue
